name: build

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    name: build

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Build
        run: npm run build
      
      - name: Push to dist branch
        run: |
          cd ./dist
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git init .
          git checkout --orphan dist
          git add .
          git commit -m "build"
          git remote add origin https://PlayDrinkEatCode:${{ secrets.GITHUB_TOKEN }}@github.com/Try-To-Create/lmlrc.git
          git push -f origin dist